language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - TWISTED=9.0.0
  - TWISTED=10.2.0
  - TWISTED=11.1.0
  - TWISTED=12.2.0
  - TWISTED=13.0.0
  - TWISTED=latest
matrix:
  exclude:
    - python: "2.5"
      env: TWISTED=12.2.0
    - python: "2.5"
      env: TWISTED=13.0.0
# command to install dependencies
install:
  - "[ $TWISTED != latest ] && pip install Twisted==$TWISTED"
  - pushd master; python setup.py develop; popd
  - pushd slave;  python setup.py develop; popd
  # Disable pylint. Latest version doesn't work on Python 2.5 
  # and currently Buildbot doesn't pass pylint tests.
  #- pip install pylint
  - pip install pyflakes
  - pip install sphinx
  # mock is preinstalled on Travis
  # txgithub requires Twisted >= 12.3.0, which doesn't work on Python 2.5.
  - "python -V 2>&1 | grep -q ' 2.5.' || pip install txgithub"
# command to run tests
script:
  - trial buildbot.test
  - trial buildslave.test
  #- make pylint
  - make pyflakes
  # At least in one place in documentation example depends on Python > 2.5,
  # so example block becomes unhighlighted.  Skip building docs on Python 2.5.
  - "python -V 2>&1 | grep -q ' 2.5.' || make docs"
